<?php declare(strict_types=1);

namespace BenRowan\PhotoTool\Service;

use BenRowan\PhotoTool\Model\Duplicates;
use BenRowan\PhotoTool\Model\File;
use BenRowan\PhotoTool\Trait\EventHookTrait;

class DuplicateFinder
{
    use EventHookTrait;

    private const CATEGORY_FILE_SIZE = 'file_size';
    private const CATEGORY_FIRST_N_BYTES = 'first_n_bytes';
    private const CATEGORY_FULL_FILE_HASH = 'full_file_hash';

    private const EVENT_START = 'start';
    private const EVENT_END = 'end';
    private const EVENT_STEP = 'step';

    /**
     * Register for file size events.
     */
    public const HOOK_FILE_SIZE_START = self::CATEGORY_FILE_SIZE . ':' . self::EVENT_START;
    public const HOOK_FILE_SIZE_END = self::CATEGORY_FILE_SIZE . ':' . self::EVENT_END;
    public const HOOK_FILE_SIZE_STEP = self::CATEGORY_FILE_SIZE . ':' . self::EVENT_STEP;

    /**
     * Register for first N bytes events.
     */
    public const HOOK_FIRST_N_BYTES_START = self::CATEGORY_FIRST_N_BYTES . ':' . self::EVENT_START;
    public const HOOK_FIRST_N_BYTES_END = self::CATEGORY_FIRST_N_BYTES . ':' . self::EVENT_END;
    public const HOOK_FIRST_N_BYTES_STEP = self::CATEGORY_FIRST_N_BYTES . ':' . self::EVENT_STEP;

    /**
     * Register for full file hash events.
     */
    public const HOOK_FULL_FILE_HASH_START = self::CATEGORY_FULL_FILE_HASH . ':' . self::EVENT_START;
    public const HOOK_FULL_FILE_HASH_END = self::CATEGORY_FULL_FILE_HASH . ':' . self::EVENT_END;
    public const HOOK_FULL_FILE_HASH_STEP = self::CATEGORY_FULL_FILE_HASH . ':' . self::EVENT_STEP;

    /**
     * Access context data on applicable events.
     */
    public const CONTEXT_FILE_COUNT = 'file_count';

    public function __construct(
        private FileSystem $fileSystem
    ) {}

    /**
     * Recursively search the provided directory for duplicate files.
     *
     * @param string $directory The directory to search.
     * 
     * @return array
     */
    public function findDuplicates(string $directory): array
    {
        $allFiles = $this->fileSystem->findFiles($directory);

        $byFileSize = $this->findDuplicatesBy(
            self::CATEGORY_FILE_SIZE,
            $allFiles,
            function (File $file) {
                return (string) $file->getTotalFileSizeBytes();
            }
        );

        $byFirstNBytes = $this->findDuplicatesBy(
            self::CATEGORY_FIRST_N_BYTES,
            $byFileSize->getAllFiles(), // Creates a flat array of Files
            function (File $file) {
                return $file->hashFirstNBytes(1000000);
            }
        );

        $byFullFileHash = $this->findDuplicatesBy(
            self::CATEGORY_FULL_FILE_HASH,
            $byFirstNBytes->getAllFiles(), // Creates a flat array of Files
            function (File $file) {
                return $file->hashFullFile();
            }
        );

        return $byFullFileHash->getDuplicates();
    }

    /**
     * Sort the files using the key generated by $generateKey
     * in order to detect duplicate files.
     *
     * @param string $category The type of key being generated.
     * @param array $files The files to check for duplicates.
     * @param callable $generateKey Generates the key used for sorting.
     * 
     * @return Duplicates
     */
    private function findDuplicatesBy(
        string $category,
        array $files,
        callable $generateKey
    ): Duplicates {

        $this->callHooks(
            sprintf('%s:%s', $category, self::EVENT_START),
            [self::CONTEXT_FILE_COUNT => count($files)]
        );

        $duplicates = new Duplicates();

        foreach ($files as $file) {
            $key = $generateKey($file);
            $duplicates->addFile($key, $file);
            $this->callHooks(sprintf('%s:%s', $category, self::EVENT_STEP));
        }

        $duplicates->pruneUniqueFiles();

        $this->callHooks(sprintf('%s:%s', $category, self::EVENT_END));

        return $duplicates;
    }
}